apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.secrets.webui.password.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: pihole
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  webpassword: {{ include "common.secrets.passwords.manage" (dict "secret" ( include "pihole.secrets.webui.password.name" $ ) "key" "webpassword" "providedValues" (list "pihole.webui.admin.password") "context" $) }}
